NAME = "skill_make_a_new_skill_to_crawl"
DESCRIPTION = "Create a new Python skill that crawls a website, extracts content, and optionally downloads files. Generates the skill code and saves it to the skills directory."
TRIGGERS = ["make a new skill to crawl", "create crawl skill", "new web crawler skill", "build a crawler", "crawl website skill", "auto-generate crawler"]

import os
import textwrap

SKILLS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)))


def run(url="", name="", max_pages=5, download_files=False, file_types="pdf,docx", **kwargs):
    """Generate a new crawl skill and save it to the skills directory.

    Args:
        url: The target website URL to crawl (e.g., "https://example.com").
        name: Name for the new skill (e.g., "crawl_example"). Auto-generated from URL if empty.
        max_pages: Maximum number of pages to crawl (default 5).
        download_files: Whether to download files found on the site (default False).
        file_types: Comma-separated file extensions to download (default "pdf,docx").

    Returns:
        Status message with the path to the created skill.
    """
    if not url:
        return "Provide a URL to crawl, e.g., url='https://example.com'"

    # Auto-generate skill name from URL
    if not name:
        from urllib.parse import urlparse
        parsed = urlparse(url)
        name = "crawl_" + parsed.netloc.replace("www.", "").replace(".", "_").replace("-", "_")

    # Sanitize name
    safe_name = "".join(c if (c.isalnum() or c == "_") else "_" for c in name)
    if not safe_name:
        safe_name = "crawl_skill"

    filepath = os.path.join(SKILLS_DIR, safe_name + ".py")

    # Generate the skill code
    code = textwrap.dedent(f'''\
    """
    Auto-generated web crawler skill for {url}.
    Created by skill_make_a_new_skill_to_crawl.
    """

    import requests
    from bs4 import BeautifulSoup
    from urllib.parse import urlparse, urljoin
    import os

    NAME = "{safe_name}"
    DESCRIPTION = "Crawl {url} and extract content. Auto-generated by Ultron."
    TRIGGERS = ["crawl {safe_name}", "scrape {url}", "fetch from {url}"]

    _BASE_URL = "{url}"
    _MAX_PAGES = {max_pages}
    _DOWNLOAD = {download_files}
    _FILE_TYPES = "{file_types}".split(",")

    def run(action="crawl", page_url=None, **kwargs):
        """Crawl the target website.

        Args:
            action: "crawl" (extract text), "links" (extract links), "download" (download files), "sitemap" (list all pages).
            page_url: Specific page to crawl. Uses base URL if None.

        Returns:
            Extracted content or status message.
        """
        target = page_url or _BASE_URL

        if action == "sitemap":
            return _sitemap(target)
        elif action == "links":
            return _extract_links(target)
        elif action == "download":
            return _download_files(target)
        else:
            return _crawl(target)

    def _crawl(url):
        try:
            resp = requests.get(url, timeout=15, headers={{"User-Agent": "Mozilla/5.0"}})
            resp.raise_for_status()
            soup = BeautifulSoup(resp.text, "html.parser")
            # Remove script/style
            for tag in soup(["script", "style", "nav", "footer"]):
                tag.decompose()
            title = soup.title.string.strip() if soup.title else "(no title)"
            texts = []
            for p in soup.find_all(["p", "h1", "h2", "h3", "li"]):
                t = p.get_text(strip=True)
                if len(t) > 20:
                    texts.append(t)
            return f"=== {{title}} ===\\n" + "\\n".join(texts[:30])
        except Exception as e:
            return f"Crawl failed: {{e}}"

    def _extract_links(url):
        try:
            resp = requests.get(url, timeout=15, headers={{"User-Agent": "Mozilla/5.0"}})
            soup = BeautifulSoup(resp.text, "html.parser")
            links = []
            for a in soup.find_all("a", href=True):
                full = urljoin(url, a["href"])
                if urlparse(full).netloc == urlparse(_BASE_URL).netloc:
                    links.append(full)
            return "\\n".join(sorted(set(links)))
        except Exception as e:
            return f"Link extraction failed: {{e}}"

    def _download_files(url):
        if not _DOWNLOAD:
            return "Download not enabled. Set download_files=True when creating the skill."
        try:
            resp = requests.get(url, timeout=15, headers={{"User-Agent": "Mozilla/5.0"}})
            soup = BeautifulSoup(resp.text, "html.parser")
            downloaded = []
            for a in soup.find_all("a", href=True):
                href = a["href"]
                if any(href.lower().endswith("." + ext.strip()) for ext in _FILE_TYPES):
                    full_url = urljoin(url, href)
                    fname = os.path.basename(urlparse(full_url).path) or "download"
                    r = requests.get(full_url, timeout=30)
                    with open(fname, "wb") as f:
                        f.write(r.content)
                    downloaded.append(fname)
            return f"Downloaded {{len(downloaded)}} files: {{', '.join(downloaded)}}" if downloaded else "No matching files found."
        except Exception as e:
            return f"Download failed: {{e}}"

    def _sitemap(url):
        visited = set()
        queue = [url]
        results = []
        while queue and len(visited) < _MAX_PAGES:
            current = queue.pop(0)
            if current in visited:
                continue
            visited.add(current)
            try:
                resp = requests.get(current, timeout=10, headers={{"User-Agent": "Mozilla/5.0"}})
                soup = BeautifulSoup(resp.text, "html.parser")
                results.append(current)
                for a in soup.find_all("a", href=True):
                    full = urljoin(current, a["href"])
                    if urlparse(full).netloc == urlparse(_BASE_URL).netloc and full not in visited:
                        queue.append(full)
            except Exception:
                continue
        return f"Found {{len(results)}} pages:\\n" + "\\n".join(results)

    if __name__ == "__main__":
        import sys
        action = sys.argv[1] if len(sys.argv) > 1 else "crawl"
        print(run(action=action))
    ''')

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(code)

    return f"Created new crawl skill: {filepath}\nUsage: {safe_name} action=crawl  (or links, download, sitemap)"


if __name__ == "__main__":
    import sys
    url = sys.argv[1] if len(sys.argv) > 1 else ""
    print(run(url=url))
